services:
  - type: web
    name: partybin
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: partybin-db
          property: connectionString
  - type: database
    name: partybin-db
    plan: free
    ipAllowList: []
